# BasicCNN-2

In [2]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time

pygame 2.1.2 (SDL 2.0.18, Python 3.7.6)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [3]:
import os
os.chdir("C://Users//pc//Desktop//Drowsiness detection//Drowsiness detection//")
mixer.init()
sound = mixer.Sound('alarm.wav')

face = cv2.CascadeClassifier('haar_cascade_files/haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haar_cascade_files/haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haar_cascade_files/haarcascade_righteye_2splits.xml')





model = load_model('models/cnnCat2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(frame,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(frame)
    right_eye =  reye.detectMultiScale(frame)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(24,24))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(24,24,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred1 = model.predict(r_eye)
        print("*******************************************************************************")
        print(rpred1)
        class_labels=['Closed','Open']
        rpred = class_labels[rpred1.argmax()]
        print("*******************************************************************************")
        print(rpred)
        if(rpred=='Open'):
            class_labels='Open' 
        if(rpred=='Closed'):
            class_labels='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(24,24))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(24,24,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred1 = model.predict(l_eye)
        print("#################################################################################")
        print(lpred1)
        class_labels=['Closed','Open']
        lpred = class_labels[lpred1.argmax()]
        print("#################################################################################")
        print(lpred)
        #if(lpred[0]==1):
        if(lpred=='Open'):
            class_labels='Open' 
        if(lpred=='Closed'):
            class_labels='Closed' 
        break
        #    lbl='Open'   
        #if(lpred[0]==0):
        #    lbl='Closed'
        #break

    #if(rpred[0]==0 and lpred[0]==0):
    if(rpred=='Closed' and lpred =='Closed'):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    #if(rpred=='Open' or lpred =='Open'):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0   
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>15):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()


*******************************************************************************
[[0.9245685  0.07543153]]
*******************************************************************************
Closed
#################################################################################
[[0.9094593  0.09054073]]
#################################################################################
Closed
*******************************************************************************
[[0.88103116 0.11896887]]
*******************************************************************************
Closed
*******************************************************************************
[[0.8894905  0.11050951]]
*******************************************************************************
Closed
*******************************************************************************
[[0.9424395  0.05756047]]
*******************************************************************************
Closed
*******************************

# VGG16

In [4]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time

In [5]:
import os
os.chdir("C://Users//pc//Desktop//Drowsiness detection//Drowsiness detection//")
mixer.init()
sound = mixer.Sound('alarm.wav')

face = cv2.CascadeClassifier('haar_cascade_files/haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haar_cascade_files/haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haar_cascade_files/haarcascade_righteye_2splits.xml')





model = load_model('models/Drowsiness_detection_vgg16.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(frame,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(frame)
    right_eye =  reye.detectMultiScale(frame)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
#         r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(224,224))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(224,224,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred1 = model.predict(r_eye)
        print("*******************************************************************************")
        print(rpred1)
        class_labels=['Closed','Open']
        rpred = class_labels[rpred1.argmax()]
        print("*******************************************************************************")
        print(rpred)
        if(rpred=='Open'):
            class_labels='Open' 
        if(rpred=='Closed'):
            class_labels='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
#         l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(224,224))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(224,224,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred1 = model.predict(l_eye)
        print("#################################################################################")
        print(lpred1)
        class_labels=['Closed','Open']
        lpred = class_labels[lpred1.argmax()]
        print("#################################################################################")
        print(lpred)
        #if(lpred[0]==1):
        if(lpred=='Open'):
            class_labels='Open' 
        if(lpred=='Closed'):
            class_labels='Closed' 
        break
        #    lbl='Open'   
        #if(lpred[0]==0):
        #    lbl='Closed'
        #break

    #if(rpred[0]==0 and lpred[0]==0):
    if(rpred=='Closed' and lpred =='Closed'):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    #if(rpred=='Open' or lpred =='Open'):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0   
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>15):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()


*******************************************************************************
[[0.6698408  0.33015922]]
*******************************************************************************
Closed
#################################################################################
[[0.49845755 0.5015425 ]]
#################################################################################
Open
#################################################################################
[[0.7469283  0.25307176]]
#################################################################################
Closed
*******************************************************************************
[[0.6322079  0.36779216]]
*******************************************************************************
Closed
#################################################################################
[[0.5609311  0.43906894]]
#################################################################################
Closed
*************************

# BasicCNN-2

In [6]:
import os
os.chdir("C://Users//pc//Desktop//Drowsiness detection//Drowsiness detection//")
mixer.init()
sound = mixer.Sound('alarm.wav')

face = cv2.CascadeClassifier('haar_cascade_files/haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haar_cascade_files/haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haar_cascade_files/haarcascade_righteye_2splits.xml')





model = load_model('models/drowsiness_detection_2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(frame,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(frame)
    right_eye =  reye.detectMultiScale(frame)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(256,256))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(256,256,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred1 = model.predict(r_eye)
        print("*******************************************************************************")
        print(rpred1)
        class_labels=['Closed','Open']
        rpred = class_labels[rpred1.argmax()]
        print("*******************************************************************************")
        print(rpred)
        if(rpred=='Open'):
            class_labels='Open' 
        if(rpred=='Closed'):
            class_labels='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(256,256))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(256,256,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred1 = model.predict(l_eye)
        print("#################################################################################")
        print(lpred1)
        class_labels=['Closed','Open']
        lpred = class_labels[lpred1.argmax()]
        print("#################################################################################")
        print(lpred)
        #if(lpred[0]==1):
        if(lpred=='Open'):
            class_labels='Open' 
        if(lpred=='Closed'):
            class_labels='Closed' 
        break
        #    lbl='Open'   
        #if(lpred[0]==0):
        #    lbl='Closed'
        #break

    #if(rpred[0]==0 and lpred[0]==0):
    if(rpred=='Closed' and lpred =='Closed'):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    #if(rpred=='Open' or lpred =='Open'):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0   
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>15):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()


*******************************************************************************
[[0.915823   0.08417698]]
*******************************************************************************
Closed
#################################################################################
[[0.7739465  0.22605355]]
#################################################################################
Closed
*******************************************************************************
[[0.9301026 0.0698974]]
*******************************************************************************
Closed
#################################################################################
[[0.9146369  0.08536306]]
#################################################################################
Closed
*******************************************************************************
[[0.94005406 0.05994596]]
*******************************************************************************
Closed
#############################

#################################################################################
[[0.9282057  0.07179427]]
#################################################################################
Closed
