In [1]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time

pygame 2.0.1 (SDL 2.0.14, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [5]:
mixer.init()
sound = mixer.Sound('C:\\Users\\Anu\\Downloads\\drowsinessdetection\\alarm.wav')

face = cv2.CascadeClassifier('C:/Users/Anu/Downloads/haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('C:/Users/Anu/Downloads/haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('C:/Users/Anu/Downloads/haarcascade_righteye_2splits.xml')





model = load_model('C:/Users/Anu/Downloads/models-20220328T165700Z-001/models/cnnCat2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(frame,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(frame)
    right_eye =  reye.detectMultiScale(frame)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(24,24))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(24,24,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred1 = model.predict(r_eye)
        print("*******************************************************************************")
        print(rpred1)
        class_labels=['Closed','Open']
        rpred = class_labels[rpred1.argmax()]
        print("*******************************************************************************")
        print(rpred)
        if(rpred=='Open'):
            class_labels='Open' 
        if(rpred=='Closed'):
            class_labels='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(24,24))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(24,24,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred1 = model.predict(l_eye)
        print("#################################################################################")
        print(lpred1)
        class_labels=['Closed','Open']
        lpred = class_labels[lpred1.argmax()]
        print("#################################################################################")
        print(lpred)
        #if(lpred[0]==1):
        if(lpred=='Open'):
            class_labels='Open' 
        if(lpred=='Closed'):
            class_labels='Closed' 
        break
        #    lbl='Open'   
        #if(lpred[0]==0):
        #    lbl='Closed'
        #break

    #if(rpred[0]==0 and lpred[0]==0):
    if(rpred=='Closed' and lpred =='Closed'):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    #if(rpred=='Open' or lpred =='Open'):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0   
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>15):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

*******************************************************************************
[[8.5228527e-07 9.9999917e-01]]
*******************************************************************************
Open
#################################################################################
[[0.00167108 0.998329  ]]
#################################################################################
Open
*******************************************************************************
[[1.8387359e-06 9.9999821e-01]]
*******************************************************************************
Open
#################################################################################
[[4.5348733e-04 9.9954647e-01]]
#################################################################################
Open
*******************************************************************************
[[0.00103936 0.9989606 ]]
*******************************************************************************
Open
###################

In [6]:
mixer.init()
sound = mixer.Sound('C:\\Users\\Anu\\Downloads\\drowsinessdetection\\alarm.wav')

In [7]:
 sound.play()

In [4]:
pwd

'C:\\Users\\Anu\\Downloads\\drowsinessdetection'

In [50]:
lbl

'Open'